FROM node:16.17.0-slim

WORKDIR /usr/src/app

EXPOSE 5000

ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8080

COPY . .

RUN npm install

RUN npm install -g serve

RUN npm run build

CMD serve -s -l 5000 build
